// <auto-generated />
using System;
using LosRalos.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LosRalos.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260709012801_AgregarCargoAreaOperativaTipoEfectorMatricula")]
    partial class AgregarCargoAreaOperativaTipoEfectorMatricula
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LosRalos.Application.Entities.AreaOperativa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("areas_operativas", (string)null);
                });

            modelBuilder.Entity("LosRalos.Application.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("DetalleExtra")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IpOrigen")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("NombreUsuario")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ProfesionalId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProfesionalId")
                        .HasDatabaseName("idx_auditlog_profesional_id");

                    b.HasIndex("Timestamp")
                        .IsDescending()
                        .HasDatabaseName("idx_auditlog_timestamp");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("idx_auditlog_usuario_id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("LosRalos.Application.Entities.Cargo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("cargos", (string)null);
                });

            modelBuilder.Entity("LosRalos.Application.Entities.Documento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CargadoPorId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreOriginal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("ProfesionalId")
                        .HasColumnType("uuid");

                    b.Property<long>("TamanioBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TipoDocumentoId")
                        .HasColumnType("uuid");

                    b.Property<string>("UrlArchivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CargadoPorId")
                        .HasDatabaseName("idx_documento_cargado_por_id");

                    b.HasIndex("ProfesionalId")
                        .HasDatabaseName("idx_documento_profesional_id");

                    b.HasIndex("TipoDocumentoId")
                        .HasDatabaseName("idx_documento_tipo_documento_id");

                    b.ToTable("documentos", (string)null);
                });

            modelBuilder.Entity("LosRalos.Application.Entities.Profesional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("AreaOperativaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Barrio")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("CargoId")
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoPostal")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Cuil")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Domicilio")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("EstadoCivil")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Matricula")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NroExpediente")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Planta")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("Tucuman");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TipoEfector")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasKey("Id");

                    b.HasIndex("Activo")
                        .HasDatabaseName("idx_profesional_activo")
                        .HasFilter("\"Activo\" = true");

                    b.HasIndex("AreaOperativaId")
                        .HasDatabaseName("idx_profesional_area_operativa");

                    b.HasIndex("CargoId")
                        .HasDatabaseName("idx_profesional_cargo");

                    b.HasIndex("Cuil")
                        .IsUnique()
                        .HasDatabaseName("uq_profesional_cuil");

                    b.HasIndex("Dni")
                        .IsUnique()
                        .HasDatabaseName("uq_profesional_dni");

                    b.HasIndex("Tipo")
                        .HasDatabaseName("idx_profesional_tipo");

                    b.ToTable("profesionales", null, t =>
                        {
                            t.HasCheckConstraint("chk_profesional_estado_civil", "\"EstadoCivil\" IN ('Soltero', 'Casado', 'Divorciado', 'Viudo', 'Otro')");

                            t.HasCheckConstraint("chk_profesional_nivel", "\"Nivel\" IN ('Secundario', 'Terciario', 'Universitario')");

                            t.HasCheckConstraint("chk_profesional_planta", "\"Planta\" IN ('Transitorio', 'PermanenteInterino', 'PermanenteEfectivo')");

                            t.HasCheckConstraint("chk_profesional_sexo", "\"Sexo\" IN ('Masculino', 'Femenino', 'Otro')");

                            t.HasCheckConstraint("chk_profesional_tipo", "\"Tipo\" IN ('Asistencial', 'NoAsistencial', 'CP')");

                            t.HasCheckConstraint("chk_profesional_tipo_efector", "\"TipoEfector\" IN ('Hospital', 'CAPS')");
                        });
                });

            modelBuilder.Entity("LosRalos.Application.Entities.TipoDocumento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("tipos_documento", (string)null);
                });

            modelBuilder.Entity("LosRalos.Application.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("uq_usuario_email");

                    b.ToTable("usuarios", null, t =>
                        {
                            t.HasCheckConstraint("chk_usuario_rol", "\"Rol\" IN ('Admin', 'Administrativo')");
                        });
                });

            modelBuilder.Entity("LosRalos.Application.Entities.AuditLog", b =>
                {
                    b.HasOne("LosRalos.Application.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LosRalos.Application.Entities.Documento", b =>
                {
                    b.HasOne("LosRalos.Application.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CargadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LosRalos.Application.Entities.Profesional", null)
                        .WithMany("Documentos")
                        .HasForeignKey("ProfesionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LosRalos.Application.Entities.TipoDocumento", "TipoDocumento")
                        .WithMany()
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("LosRalos.Application.Entities.Profesional", b =>
                {
                    b.HasOne("LosRalos.Application.Entities.AreaOperativa", "AreaOperativa")
                        .WithMany()
                        .HasForeignKey("AreaOperativaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LosRalos.Application.Entities.Cargo", "Cargo")
                        .WithMany()
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AreaOperativa");

                    b.Navigation("Cargo");
                });

            modelBuilder.Entity("LosRalos.Application.Entities.Profesional", b =>
                {
                    b.Navigation("Documentos");
                });
#pragma warning restore 612, 618
        }
    }
}
